theme: jekyll-theme-midnight
title: "Template"
description: "Frank P Leuck and Judith Sherwood Leuck reunion site and blog."
gitorg: "https://github.com/jm1021/leuck_reunion"
description: "Description"
google_analytics:
